apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: webhook-server-cert
  files:
    - certs/tls.crt
    - certs/tls.key
  type: "kubernetes.io/tls"

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: ca-cert
  files:
  - certs/ca.pem.b64

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
vars:
  - name: CA_CERT_B64
    objref:
      kind: ConfigMap
      name: ca-cert
      apiVersion: v1
    fieldref:
      fieldpath: data.[ca.pem.b64]

resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml