
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-paas-il-v1beta1-managedresource
  failurePolicy: Fail
  name: mmanagedresource.kb.io
  rules:
  - apiGroups:
    - paas.il
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedresources

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-paas-il-v1beta1-managedresource
  failurePolicy: Fail
  name: vmanagedresource.kb.io
  rules:
  - apiGroups:
    - paas.il
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedresources
