# permissions for end users to edit managedresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedresource-editor-role
rules:
- apiGroups:
  - paas.il
  resources:
  - managedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.il
  resources:
  - managedresources/status
  verbs:
  - get
