
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - paas.il
  resources:
  - managedresourcebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paas.il
  resources:
  - managedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.il
  resources:
  - managedresources/status
  verbs:
  - get
  - patch
  - update
