apiVersion: paas.il/v1beta1
kind: ManagedResourceBinding
metadata:
  name: managedresourcebinding-sample
spec:
  items:
  - object:
      kind: CustomResourceDefinition
      metadata:
        name: tests.example.com
    verbs:
    - create
    - update
    - delete
  namespaces:
  - default
