apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: managed-resource-operator-manager-rolebinding-cm-crd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: managed-resource-operator-manager-role-cm-crd
subjects:
- kind: ServiceAccount
  name: default
  namespace: managed-resource-operator-system
