apiVersion: paas.il/v1beta1
kind: ManagedResourceBinding
metadata:
  name: managedresourcebinding-cm-crd
spec:
  items:
  - object:
      kind: CustomResourceDefinition
      metadata:
        name: tests.example.com
    verbs:
    - create
    - delete
  - object:
      kind: ConfigMap
      metadata:
        name: "*"
        namespace: default
    verbs:
    - create
    - delete
  namespaces:
  - "*"
