apiVersion: paas.il/v1beta1
kind: ManagedResourceBinding
metadata:
  name: managedresourcebinding-cm-crd
spec:
  objects:
  - kind: CustomResourceDefinition
    metadata:
      name: tests.example.com
  - kind: ConfigMap
    metadata:
      name: "*"
      namespace: default
  namespaces:
  - "*"
